pub mod auth_service;
pub mod cloudinary_service;
pub mod database_status_service;
pub mod main_class_service;
pub mod sector_service;
pub mod student_service;
pub mod subjects;
pub mod trade_service;
pub mod user_service;
